[package]
name = "pure-evm-wasm"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pure-evm = { path = "../" }
wasm-bindgen = "0.2.55"